### ISSUE TITLE
GPU-enabled CPU for training-only

### ISSUE THREAD

**Issue by jojo05** [paucarre/tiefvision#25]
Hi,

I assume the GPU is only required for training but not for the runtime? Is this correct?

gracies

**Comment by Plippe** [comment]
Hi,

Sorry for the long delay.

Not 100% sure of which part of the code you are talking about, but most of the times there is a caching phase and a lookup one:
- cache
  - https://github.com/paucarre/tiefvision/tree/master/src/torch/9-similarity-db
  - https://github.com/paucarre/tiefvision/tree/master/src/torch/14-deeprank-db

- lookup
  - https://github.com/paucarre/tiefvision/tree/master/src/torch/10-similarity-searcher-cnn-db
  - https://github.com/paucarre/tiefvision/tree/master/src/torch/15-deeprank-searcher-db

The caching phase does all the heavy lifting and currently requires a GPU. Once finished, you should have a cache populated with all the results. The lookup phase uses those results and doesn't calculate anything. 

So you are right, the GPU is only required at the start.

**Comment by paucarre** [comment]
Totally right with @Plippe just keep in mind that if you want to do real time similarity inference ( https://github.com/paucarre/tiefvision/blob/master/src/torch/11-similarity-searcher-cnn-file/search.lua ) now you need GPU right now. 
We'll most likely enable toggling GPU to enable inference using only CPU.
