### ISSUE TITLE
module 'loadcaffe' not found:

### ISSUE THREAD

**Issue by himanshurobo** [paucarre/tiefvision#43]
I run luajit split-encoder-classifier.lua. i found error loadcaffe not found ?? 
luajit: split-encoder-classifier.lua:14: module 'loadcaffe' not found:
	no field package.preload['loadcaffe']
	no file '/home/stylabs/.luarocks/share/lua/5.1/loadcaffe.lua'
	no file '/home/stylabs/.luarocks/share/lua/5.1/loadcaffe/init.lua'
	no file '/home/stylabs/torch/install/share/lua/5.1/loadcaffe.lua'
	no file '/home/stylabs/torch/install/share/lua/5.1/loadcaffe/init.lua'
	no file './loadcaffe.lua'
	no file '/home/stylabs/torch/install/share/luajit-2.1.0-beta1/loadcaffe.lua'
	no file '/usr/local/share/lua/5.1/loadcaffe.lua'
	no file '/usr/local/share/lua/5.1/loadcaffe/init.lua'
	no file '/home/stylabs/tiefvision/src/torch/loadcaffe.lua'
	no file '/home/stylabs/torch/install/lib/loadcaffe.so'
	no file '/home/stylabs/.luarocks/lib/lua/5.1/loadcaffe.so'
	no file '/home/stylabs/torch/install/lib/lua/5.1/loadcaffe.so'
	no file './loadcaffe.so'
	no file '/usr/local/lib/lua/5.1/loadcaffe.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	split-encoder-classifier.lua:14: in main chunk
	[C]: at 0x00405d50

What is the error and how to solve it

**Comment by paucarre** [comment]
you have to install https://github.com/szagoruyko/loadcaffe using into your local torch lua install using luarocks
