### ISSUE TITLE
 module 'inn' not found: 

### ISSUE THREAD

**Issue by himanshurobo** [paucarre/tiefvision#46]
I tried to install 
"luarocks install inn" but i found error

Installing https://raw.githubusercontent.com/torch/rocks/master/inn-1.0-0.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/inn-1.0-0.rockspec... switching to 'build' mode
Cloning into 'imagine-nn'...
remote: Counting objects: 27, done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 27 (delta 1), reused 9 (delta 0), pack-reused 0
Receiving objects: 100% (27/27), 15.26 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1/1), done.
Checking connectivity... done.
cmake -E make_directory build;
cd build;
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/stylabs/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/stylabs/torch/install/lib/luarocks/rocks/inn/1.0-0"; 
make
   
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Torch7 in /home/stylabs/torch/install
-- Found CUDA: /usr (found suitable version "7.5", minimum required is "6.5") 
-- Compiling for CUDA architecture: 3.5
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/luarocks_inn-1.0-0-1407/imagine-nn/build
[ 33%] Building NVCC (Device) object CMakeFiles/inn.dir/inn_generated_ROIPooling.cu.o
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
CMake Error at inn_generated_ROIPooling.cu.o.cmake:267 (message):
  Error generating file
  /tmp/luarocks_inn-1.0-0-1407/imagine-nn/build/CMakeFiles/inn.dir//./inn_generated_ROIPooling.cu.o

CMakeFiles/inn.dir/build.make:70: recipe for target 'CMakeFiles/inn.dir/inn_generated_ROIPooling.cu.o' failed
make[2]: *** [CMakeFiles/inn.dir/inn_generated_ROIPooling.cu.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/inn.dir/all' failed
make[1]: *** [CMakeFiles/inn.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Error: Build error: Failed building.

**Comment by paucarre** [comment]
that seems to be problem with inn rather the project itself. Are you using luarocks from torch repo or from the linux distro?

**Comment by himanshurobo** [comment]
@paucarre yes. I install from torch repo and install with CUDA. I tried to install with [inn repo](https://github.com/szagoruyko/imagine-nn) but still its shows the same error. 

Could please help.

**Comment by paucarre** [comment]
which cuda version and gcc version are you using?
Keep in mind if you use GCC 5, you have to use CUDA 8.
take a look at https://github.com/BVLC/caffe/issues/4046

**Comment by paucarre** [comment]
Closing the issue as it's not Tiefvision-related but rather inn.
