### ISSUE TITLE
Image preprocessing issue

### ISSUE THREAD

**Issue by grandison** [paucarre/tiefvision#50]
There was an error during  encoding of this image [http://i.imgur.com/fOVWBs4.jpg](url).
The error has been encountered in this line `bgrImage[{ 1, {}, {} }] = scaledImage[{ 3, {}, {} }]`

Traceback:
> luajit: bad argument #2 to '?' (index out of bound at /root/torch/pkg/torch/generic/Tensor.c:971)
stack traceback:
	[C]: at 0x7fb3878b6850
	[C]: in function '__index'
	./0-tiefvision-commons/tiefvision_commons.lua:82: in function 'preprocess'
	./0-tiefvision-commons/tiefvision_commons.lua:73: in function 'loadImage'
	./8-similarity-db-cnn/similarity_db_lib.lua:26: in function 'encodeImage'
	8-similarity-db-cnn/generate-similarity-db.lua:30: in function 'createDb'
	8-similarity-db-cnn/generate-similarity-db.lua:66: in main chunk

**Comment by paucarre** [comment]
Make sure your image is RGB (it's not grey scale encoded and has no alpha channel)

**Comment by paucarre** [comment]
Just to confirm, that image is grayscale, which is not supported. it should be RGB:
```
identify --vervose fOVWBs4.jpg 
fOVWBs4.jpg JPEG 600x600 600x600+0+0 8-bit Gray 256c 36.5KB 0.000u 0:00.009
```
