### ISSUE TITLE
Downloading models and dataset

### ISSUE THREAD

**Issue by dhimanpd** [paucarre/tiefvision#51]
Hi,

While trying to follow steps given in developer.md, I got stuck in Transfer Learning step.
It could not find nin_imagenet.caffemodel required in split-encoder-classifier.lua

Please let me know if there is any tool to download dataset and model files required to reproduce you results.

Thanks,
Prince

**Comment by Plippe** [comment]
Hi,

You can find download links for all of those in [bin/unsupervised_similarity](https://github.com/paucarre/tiefvision/blob/master/bin/unsupervised_similarity). The script is still a work in progress, but it does show the simplest way to run unsupervised similarity.

Don't hesitate to ask if you need more help.

**Comment by jteng** [comment]
@Plippe thanks!
