### ISSUE TITLE
Local features

### ISSUE THREAD

**Issue by njss** [paucarre/tiefvision#52]
Hello,

really great work!
Have you tried to accomplish image similarity search based on local features?
Searching for parts of an object for example in a collection of images would be a good use case.

best,

Nelson

**Comment by Plippe** [comment]
Hi,

Thank you for your feedback. 

I am sorry to say that tiefvision will never identify features. It was just never built to do that.
We are building other tools that identify features, but none of them are currently open to the public. 

Who knows, we might have something to share in the future.

**Comment by njss** [comment]
I understand, Thank you!
