### ISSUE TITLE
Transfer Learning issue

### ISSUE THREAD

**Issue by adelattia** [paucarre/tiefvision#55]
Hi, 
I tried to follow the steps in developer.md, I encountred a problem after : 

```
cd $TIEFVISION_HOME/src/torch/1-split-encoder-classifier
luajit split-encoder-classifier.lua
```

this is the error I got : 
```

THCudaCheck FAIL file=/home/dim/torch/extra/cutorch/lib/THC/THCGeneral.c line=66 error=35 : CUDA driver version is insufficient for CUDA runtime version
luajit: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at /home/dim/torch/extra/cutorch/lib/THC/THCGeneral.c:66
stack traceback:
	[C]: at 0x7f8d34a44720
	[C]: in function 'require'
	/home/dim/torch/install/share/lua/5.1/cutorch/init.lua:2: in main chunk
	[C]: in function 'require'
	/home/dim/torch/install/share/lua/5.1/cunn/init.lua:3: in main chunk
	[C]: in function 'require'
	/home/dim/torch/install/share/lua/5.1/inn/ffi.lua:6: in main chunk
	[C]: in function 'require'
	/home/dim/torch/install/share/lua/5.1/inn/init.lua:3: in main chunk
	[C]: in function 'require'
	split-encoder-classifier.lua:16: in main chunk
	[C]: at 0x00405d50

```
PS : I'm using cuda 8.0

Thanks,

**Comment by paucarre** [comment]
Which GPU and GPU driver do you have installed?

**Comment by adelattia** [comment]
GPU : nvidia Quadro FX 1080
GPU driver : 340.101

**Comment by paucarre** [comment]
I cannot find that card in https://developer.nvidia.com/cuda-gpus 
You will have to check first the 'compute capability' of the card and base on that install the CUDA driver that is highest and is compatible with your compute capability. Each nVIdia driver and CUDA release (check nVidia doc) has a matrix of compute capabilities which you should check and make sure your graphics card is compatible with.

**Comment by adelattia** [comment]
Hello again, the gpu is nvidia Quadro FX 1800 (**not 1080**) I made a typo there.
So apparently the gpu is a little bit old. I tried again in the laptop of a friend of mine with this config :
gpu : GeForce 840M
gpu driver : 375.26
(I double checked this time)
but now I have a new error after the same step : 
```
Couldn't load /home/ubuntu/Softs/tiefvision/src/torch/1-split-encoder-classifier/nin_imagenet.caffemodel
luajit: split-encoder-classifier.lua:27: attempt to index a nil value
stack traceback:
	split-encoder-classifier.lua:27: in main chunk
	[C]: at 0x00405d50
```
(cuda 8.0, ubuntu 16.04)

Thanks again,

**Comment by paucarre** [comment]
You need to download the reference model.
For a complete sequence of commands to do that you can take a look at `https://github.com/paucarre/tiefvision/blob/master/bin/unsupervised_similarity` or just run that script

**Comment by adelattia** [comment]
Thanks, everything works perfectly :)
