### ISSUE TITLE
bounding box models?

### ISSUE THREAD

**Issue by tpeng** [paucarre/tiefvision#61]
hi, in bboxlib.lua it loads several models by:

```
local function loadLocator(index)
  return torch.load(tiefvision_commons.modelPath('locatorconv-' .. index .. '.model'))
end

local function loadClassifier()
  return torch.load(tiefvision_commons.modelPath('classifier.model'))
end

local function loadEncoder()
  return torch.load(tiefvision_commons.modelPath('encoder.model'))
end
```
do you have pre-trained models so i can download?

thanks,

**Comment by pvinchon** [comment]
Hi Terry,

We wouldn't have any models to share, but they are quite easy to generate.

I would advise you to look at [bin/unsupervised_similarity](https://github.com/paucarre/tiefvision/blob/master/bin/unsupervised_similarity). This file has everything you need to get started. 

Good luck

**Comment by tpeng** [comment]
thanks Plippe!
